### PR TITLE
build: fix update action on forked repos

### PR DESCRIPTION
**Pull request by thcrack**
🤔

### CODE REVIEW

**Review by ikatyang — APPROVED** [review]

**Comment by ikatyang** [comment]
Thanks!

**Review by staffserg — COMMENTED** [review]
Awesome

**Review by foxcoolee — APPROVED** [review]

**Review by mohfarukranabappy — COMMENTED** [review]
update support today

**Review by labsimilk — COMMENTED** [review]
@foxcoolee

**Review by friesephillip78-ctrl — APPROVED** [review]

**Pull request merged**
