### PR TITLE
Y

### PR DESCRIPTION
**Pull request by Adminnn76**
user:defunkt

### CODE REVIEW

**Review by Kingcasper478 — APPROVED** [review]
Thanks

**Comment by Kingcasper478** [comment]
Now

**Review by Kingcasper478 — COMMENTED** [review]
Help me get my money

**Comment by Danshook1981** [comment]
> [2a5fad6](https://github.com/ikatyang/emoji-cheat-sheet/commit/2a5fad62b2f1f38098dd73991479dcae7b2e3324)

**Pull request merged**
