### PR TITLE
Skiptomain.md

### PR DESCRIPTION
**Pull request by Brosaka91**
/^(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)(?:-(?P<prerelease>(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+(?P<buildmetadata>[0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$
Android 12/gm

### CODE REVIEW

**Comment by Brosaka91** [comment]
> 

> #

**Comment by Brosaka91** [comment]
/^(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)(?:-(?P<prerelease>(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+(?P<buildmetadata>[0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$
Android 12/gm

**Comment by Brosaka91** [comment]
https://regex101.com/r/Ly7O1x/1161

**Comment by Brosaka91** [comment]
#517

**Review by Davoudkhorram — APPROVED** [review]

**Comment by Rohit484** [comment]
....

**Review by Kobra1370 — APPROVED** [review]

**Comment by Kobra1370** [comment]
#332

**Comment by Kobra1370** [comment]
#549

**Review by Kobra1370 — COMMENTED** [review]
[SECURITY.md](www.)

**Review by Kaze-1 — APPROVED** [review]

**Comment by Zhila136** [comment]
😆🇹🇷🇹🇷

**Review by Zhila136 — COMMENTED** [review]
😆😆🙏🙏🙏

**Review by Rohit484 — APPROVED** [review]

**Pull request closed without merging**
